//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSchoolService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versicherungspaket
    {
        public Versicherungspaket()
        {
            this.Fahrzeug = new HashSet<Fahrzeug>();
        }
    
        public int VersicherungspaketID { get; set; }
        public string Bezeichnung { get; set; }
        public bool Insassenunfallschutzversicherung { get; set; }
        public bool Haftpflichtversicherung { get; set; }
        public bool Feuerversicherung { get; set; }
        public bool Haftungsbegrenzung { get; set; }
        public bool Diebstahlschutz { get; set; }
    
        public virtual ICollection<Fahrzeug> Fahrzeug { get; set; }
    }
}
