//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class peterson_infrastrukturDBEntities : DbContext
    {
        public peterson_infrastrukturDBEntities()
            : base("name=peterson_infrastrukturDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresse> Adresse { get; set; }
        public DbSet<Anmeldung> Anmeldung { get; set; }
        public DbSet<Auftrag> Auftrag { get; set; }
        public DbSet<Benutzer> Benutzer { get; set; }
        public DbSet<Benutzerart> Benutzerart { get; set; }
        public DbSet<Fahrzeug> Fahrzeug { get; set; }
        public DbSet<Fahrzeugtyp> Fahrzeugtyp { get; set; }
        public DbSet<Kontakt> Kontakt { get; set; }
        public DbSet<Kunde> Kunde { get; set; }
        public DbSet<Versicherungspaket> Versicherungspaket { get; set; }
    }
}
