//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeug
    {
        public Fahrzeug()
        {
            this.Auftrag = new HashSet<Auftrag>();
        }
    
        public int FahrzeugID { get; set; }
        public int FahrzeugtypID { get; set; }
        public int VersicherungspaketID { get; set; }
        public string Bezeichnung { get; set; }
        public string Marke { get; set; }
        public int Baujahr { get; set; }
        public double Kilometerstand { get; set; }
        public string Schaltung { get; set; }
        public int Sitze { get; set; }
        public int Türe { get; set; }
        public bool Naviagationssystem { get; set; }
        public bool Klimaanlage { get; set; }
        public double MietpreisProTag { get; set; }
        public bool Verfügbar { get; set; }
    
        public virtual ICollection<Auftrag> Auftrag { get; set; }
        public virtual Fahrzeugtyp Fahrzeugtyp { get; set; }
        public virtual Versicherungspaket Versicherungspaket { get; set; }
    }
}
