//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalEbertsonService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anmeldung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anmeldung()
        {
            this.Benutzer = new HashSet<Benutzer>();
        }
    
        public int AnmeldungID { get; set; }
        public string Benutzername { get; set; }
        public string Passwort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Benutzer> Benutzer { get; set; }
    }
}
