//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalEbertsonService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftrag
    {
        public int AuftragID { get; set; }
        public int KundeID { get; set; }
        public int FahrzeugID { get; set; }
        public System.DateTime Auftragsdatum { get; set; }
        public System.DateTime Rückgabedatum { get; set; }
        public double Gesamtpreis { get; set; }
    
        public virtual Fahrzeug Fahrzeug { get; set; }
        public virtual Kunde Kunde { get; set; }
    }
}
