//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalEbertsonService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fahrzeug()
        {
            this.Auftrag = new HashSet<Auftrag>();
        }
    
        public int FahrzeugID { get; set; }
        public int FahrzeugtypID { get; set; }
        public int VersicherungspaketID { get; set; }
        public string Bezeichnung { get; set; }
        public string Marke { get; set; }
        public int Baujahr { get; set; }
        public double Kilometerstand { get; set; }
        public string Schaltung { get; set; }
        public int Sitze { get; set; }
        public int Türe { get; set; }
        public bool Naviagationssystem { get; set; }
        public bool Klimaanlage { get; set; }
        public double MietpreisProTag { get; set; }
        public bool Verfügbar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auftrag> Auftrag { get; set; }
        public virtual Fahrzeugtyp Fahrzeugtyp { get; set; }
        public virtual Versicherungspaket Versicherungspaket { get; set; }
    }
}
