//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalEbertsonService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunde()
        {
            this.Auftrag = new HashSet<Auftrag>();
        }
    
        public int KundeID { get; set; }
        public int KontaktID { get; set; }
        public int AdresseID { get; set; }
        public string Vornamen { get; set; }
        public string Nachnamen { get; set; }
        public int Alter { get; set; }
        public string Geschlecht { get; set; }
        public string Kundennummer { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auftrag> Auftrag { get; set; }
        public virtual Kontakt Kontakt { get; set; }
    }
}
