//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalEbertsonService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carRentalEbertsonDBEntities : DbContext
    {
        public carRentalEbertsonDBEntities()
            : base("name=carRentalEbertsonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresse { get; set; }
        public virtual DbSet<Anmeldung> Anmeldung { get; set; }
        public virtual DbSet<Auftrag> Auftrag { get; set; }
        public virtual DbSet<Benutzer> Benutzer { get; set; }
        public virtual DbSet<Benutzerart> Benutzerart { get; set; }
        public virtual DbSet<Fahrzeug> Fahrzeug { get; set; }
        public virtual DbSet<Fahrzeugtyp> Fahrzeugtyp { get; set; }
        public virtual DbSet<Kontakt> Kontakt { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
        public virtual DbSet<Versicherungspaket> Versicherungspaket { get; set; }
    }
}
